apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.46.0

directories:
- path: skills/brainstorming
  contents:
  - path: .
    git:
      url: https://github.com/obra/superpowers.git
      ref: origin/main
      depth: 1
    newRootPath: skills/brainstorming

- path: skills/dispatching-parallel-agents
  contents:
  - path: .
    git:
      url: https://github.com/obra/superpowers.git
      ref: origin/main
      depth: 1
    newRootPath: skills/dispatching-parallel-agents

- path: skills/domain-modeling
  contents:
  - path: .
    git:
      url: https://github.com/mattpocock/skills.git
      ref: origin/main
      depth: 1
    newRootPath: skills/engineering/domain-modeling

- path: skills/executing-plans
  contents:
  - path: .
    git:
      url: https://github.com/obra/superpowers.git
      ref: origin/main
      depth: 1
    newRootPath: skills/executing-plans
